export const MAIN_CATEGORY_CHOOSE = 'MAIN_CATEGORY_CHOOSE';
export const SUB_CATEGORY_CHOOSE = 'SUB_CATEGORY_CHOOSE';
export const CATEGORY_RESET = 'CATEGORY_RESET';
export const MAIN_CATEGORY_RESET = 'MAIN_CATEGORY_RESET';
export const SUB_CATEGORY_RESET = 'SUB_CATEGORY_RESET';

export const GET_SEARCH_RESULT = 'GET_SEARCH_RESULT';
export const GET_SEARCH_RESULT_SUCCESS = 'GET_SEARCH_RESULT_SUCCESS';
export const GET_SEARCH_RESULT_FAILURE = 'GET_SEARCH_RESULT_FAILURE';

export const LIKE_CLICK = 'LIKE_CLICK';

export const POST_ITEM_URL = 'POST_ITEM_URL';
export const POST_ITEM_URL_SUCCESS = 'POST_ITEM_URL_SUCCESS';
export const POST_ITEM_URL_FAILURE = 'POST_ITEM_URL_FAILURE';
