export const MAIN_CATEGORY_CHOOSE = 'MAIN_CATEGORY_CHOOSE';
export const SUB_CATEGORY_CHOOSE = 'SUB_CATEGORY_CHOOSE';
export const CATEGORY_RESET = 'CATEGORY_RESET';

export const POST_SEARCH_RESURT = 'POST_SEARCH_RESURT';
export const POST_SEARCH_RESURT_SUCCESS = 'POST_SEARCH_RESURT_SUCCESS';
export const POST_SEARCH_RESURT_FAILURE = 'POST_SEARCH_RESURT_FAILURE';
