export const MAIN_CATEGORY_CHOOSE = 'MAIN_CATEGORY_CHOOSE';
export const SUB_CATEGORY_CHOOSE = 'SUB_CATEGORY_CHOOSE';
export const CATEGORY_RESET = 'CATEGORY_RESET';
export const MAIN_CATEGORY_RESET = 'MAIN_CATEGORY_RESET';
export const SUB_CATEGORY_RESET = 'SUB_CATEGORY_RESET';

export const GET_SEARCH_RESULT = 'GET_SEARCH_RESULT';
export const GET_SEARCH_RESULT_SUCCESS = 'GET_SEARCH_RESULT_SUCCESS';
export const GET_SEARCH_RESULT_FAILURE = 'GET_SEARCH_RESULT_FAILURE';

export const POST_ITEM_URL = 'POST_ITEM_URL';
export const POST_ITEM_URL_SUCCESS = 'POST_ITEM_URL_SUCCESS';
export const POST_ITEM_URL_FAILURE = 'POST_ITEM_URL_FAILURE';

export const LIKE_WISH_ITEM = 'LIKE_WISH_ITEM';
export const LIKE_WISH_ITEM_SUCCESS = 'LIKE_WISH_ITEM_SUCCESS';
export const LIKE_WISH_ITEM_FAILURE = 'LIKE_WISH_ITEM_FAILURE';

export const DISLIKE_WISH_ITEM = 'DISLIKE_WISH_ITEM';
export const DISLIKE_WISH_ITEM_SUCCESS = 'DISLIKE_WISH_ITEM_SUCCESS';
export const DISLIKE_WISH_ITEM_FAILURE = 'DISLIKE_WISH_ITEM_FAILURE';
